# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.define "bworker" do |m|
    m.vm.hostname = "bworker"
    m.vm.network "private_network", ip: "192.168.33.15"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "bworker"
    end
    config.vm.network "forwarded_port", id:"SSH",
      guest_ip: "192.168.33.15", guest: 22,
      host_ip: "192.168.1.75", host: 3315
    config.vm.provision "shell" do |s|
            s.path = "../setup/setup.sh"
    end
  end
end
