# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.define "aworker" do |m|
    m.vm.hostname = "aworker"
    m.vm.network "private_network", ip: "192.168.33.14"
    m.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "aworker"
    end
    config.vm.network "forwarded_port", id:"SSH",
      guest_ip: "192.168.33.14", guest: 22,
      host_ip: "192.168.1.73", host: 3314
    config.vm.provision "shell" do |s|
            s.path = "../../setup.sh"
    end
  end
end
